# Default configuration file for the JSON API extension.

# List the contenttypes that are to be served through the JSON extension.
# Only contenttypes listed here will be served; for any other contenttype,
# the API will return errors.
contenttypes:
    entries:
        # The `list-fields` setting allows you to override the fields that
        # appear in listings. You can add fields as well as taxonomies.
        list-fields: [ title, slug, teaser, image, tags, categories ]
        # The `item-fields` setting allows you to override the fields that
        # appear in singular item request. Leave empty to show all fields.
        # item-fields: [ title, slug, teaser, image, teaser, body, tags, categories ]
        # The `allowed-fields` setting allows you to set what fields can be
        # shown when using the `fields[entries]` query parameter.
        allowed-fields: [ title, slug, teaser, image ]
        # The `where-clause` setting is useful, if you want to add additional
        # filters by default. These can be overridden using the `filter[entries]`
        # query parameter.
        where-clause:
            status: 'published'
    pages:
        # To use the defaults for a contenttype, just leave its entry empty.
        # This will include all user-defined fields and taxonomies in the
        # listing, but not any of the fields Bolt adds to all content types,
        # such as 'datecreated'.
    programmaonderdelen:
        where-clause:
            datepublish: '>2015-01-01'

    speeltijden:
        list-fields: [ title, slug, image, starttijd, lengte, programmaonderdelen, programmas, speellokatie, datepublish, class ]
        item-fields: [ title, slug, image, starttijd, lengte, programmaonderdelen, programmas, speellokatie, datepublish, class ]
        where-clause:
            # starttijd: '>2015-01-01'
            programmas: 4 # is into-the-great-wide-open-2015
            status: published
        order: title

    berichten:
        where-clause:
            status: 'published'
        order: -datepublish
        list-fields: [ id, title, subtitle, slug, teaser, image, tags, categories, datepublish ]

thumbnail:
    width: 240
    height: 180

headers:
    'Access-Control-Allow-Origin': '*'
    'Content-Type': 'application/vnd.api+json'

# The base url where the API is accessible.
base: '/json'

# If you set this to 'true', all datetime fields will be formatted as ISO 8601 dates
date-iso-8601: true
