database:
  driver: mysql
  databasename: greatwide_bolt
  username: greatwide_dev
  password: cAO0o00Q
  
  
homepage: pagina/itgwo
homepage_template: homepage.twig
notfound: pagina/itgwo

debug: true

maintenance_mode: false

thumbnails:
  default_thumbnail: [ 160, 120 ]
  default_image: [ 1000, 750 ]
  quality: 65
  cropping: crop
  notfound_image: view/img/default_notfound.png
  error_image: view/img/default_error.png
  save_files: true
  allow_upscale: false

