database:
  driver: mysql
  databasename: greatwide_progrm
  username: greatwide_progrm
  password: NoNygxESU

homepage: pagina/itgwo
homepage_template: homepage.twig
notfound: pagina/itgwo

debug: true

maintenance_mode: false
