berichten:
    name: Berichten
    singular_name: Bericht
    fields:
        title:
            type: text
            class: large
            group: Tekst
        slug:
            type: slug
            uses: title
        subtitle:
            type: text
            class: large
            group: Tekst
        colorselect:
            type: select
            values: [ wit, zwart ]
            label: Kleur tekst en logo focusartikel
            group: Tekst
        teaser:
            type: html
            height: 150px
            group: Tekst
        body:
            type: html
            height: 300px
            group: Tekst
        showauthor:
            type: text
            variant: inline
            label: Auteur
            postfix: "Als hier een naam staat wordt deze getoond i.p.v. jouw redactienaam"
            group: Tekst
        showauthorurl:
            type: text
            variant: inline
            label: Link website auteur (incl. http://)
            group: Tekst
        credits:
            type: text
            variant: inline
            postfix: "Bronvermelding, oorspronkelijke auteur of rechthebbende"
            group: Tekst
        video:
            type: video
            label: Plak Vimeo of Youtube url (geen embedcode dus)
            group: Media
        videotitle:
            type: text
            variant: inline
            label: Omschrijving van de video
            group: Media
            postfix: "<hr>"
        image:
            type: image
            label: Afbeelding
            group: Media
        showphotographer:
            type: text
            variant: inline
            label: Credit fotograaf hoofdfoto
            group: Media
            postfix: "<hr>"
        gallery:
            type: imagelist
            group: Media
            label: Fotoserie
            postfix: "Maak liever een -mediaitem- aan en koppel die aan dit bericht<hr>"
        spotify_link:
            type: text
            variant: inline
            label: Spotify url (http link)
            group: Media
        embed:
            type: text
            variant: inline
            label: Ruimte voor een embedcode (bijv. Soundcloud of Bandcamp)
            group: Media
    relations:
        media:
            multiple: true
            label: Kies een of meer media-items
    taxonomy: [ categorieen, tags ]
    record_template: item_bericht.twig
    listing_template: listing_berichten.twig
    listing_records: 10
    sort: datepublish DESC
    recordsperpage: 20
    icon_many: "fa:file-text-o"
    icon_one: "fa:files-o"


programma:
    name: Programmas
    singular_name: Programma
    fields:
        title:
            type: text
            class: large
        slug:
            type: slug
            uses: title
        subtitle:
            type: text
            class: large
        frontpageselect:
            type: checkbox
            label: Uitlichten op voorpagina
        colorselect:
            type: select
            values: [ wit, zwart ]
            label: Kleur tekst en logo voor deze programmaheader
        ticketlink:
            type: text
            class: large
            label: Link naar de ticketpagina (bijv. /tickets)
        image:
            type: image
        image2:
            type: image
            label: Logo: Een png32 versie (transparant dus) van het programmalogo
        image3:
            type: image
            label: Blokkenschema (afbeelding van het blokkenschema)
        teaser:
            type: html
            height: 150px
        body:
            type: html
            height: 300px
        spotifylist:
            type: text
            class: large
        deezerlist:
            type: text
            class: large
        blokkenschema:
            type: file
            class: large
            label: Blokkenschema (pdf)
        datum:
            type: date
            postfix: "De datum van deze editie (om te kunnen sorteren)"
    record_template: pagina_programma.twig
    listing_template: listing_programmas.twig
    taxonomy: [ chapters ]
    sort: -datum
    listing_records: 100
    recordsperpage: 100
    searchable: true # Toon niet in "search"
    # show_in_menu: false # Toon niet in de sidebar in Bolt
    # show_on_dashboard: false # Toon niet op dashboard
    icon_many: "fa:music"
    icon_one: "fa:music"



programmaonderdelen:
    name: Programmaonderdelen
    singular_name: Programmaonderdeel
    fields:
        name:
            type: text
            class: large
            group: Tekst
        slug:
            type: slug
            uses: name
        description:
            type: html
            height: 150px
            label: Bandtekstje
            group: Tekst
        url:
            type: text
            variant: inline
            label: website van dit programmaonderdeel
            group: Tekst
        image:
            type: image
            label: Afbeelding
            group: Media
        showphotographer:
            type: text
            variant: inline
            label: Credit fotograaf
            group: Media
            postfix: "<hr>"
        video:
            type: video
            label: Plak Vimeo of Youtube url (geen embedcode dus)
            group: Media
        videotitle:
            type: text
            variant: inline
            label: Omschrijving van de video
            group: Media
            postfix: "<hr>"
        embed:
            type: textarea
            variant: inline
            label: Ruimte voor een embedcode (bijv. Soundcloud)
            group: Media
            height: 40px
        spotify_link:
            type: text
            variant: inline
            label: Spotify url (http link)
            group: Media
        oldvideo:
            type: text
            variant: inline
            label: oude video
            postfix: LET OP! Als hier een link instaat, plak deze dan met de hand naar 'Plak Vimeo of Youtube url', hierboven.
            group: Media
            postfix: "<hr>"
    record_template: item_programmaonderdeel.twig
    listing_template: listing_programma.twig
    taxonomy: [ tags, programmatypen ]
    relations:
        programma:
            multiple: true
            label: Kies het programma waar dit onderdeel bij hoort
    listing_records: 100
    recordsperpage: 100
    icon_many: "fa:music"
    icon_one: "fa:music"
    
speeltijden:
    name: Speeltijden
    singular_name: Speeltijd
    fields:
        title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
        image:
            type: image
            label: Afbeelding
        starttijd:
            type: datetime
            variant: inline
            label: Speeldag en starttijd
            postfix: AM is voor de middag, PM is na de middag
        lengte:
            type: integer
            variant: inline
            label: Speelduur
            postfix: "Lengte van het optreden / performance. In minuten, dus '2 uur' is '120'."
        programmaonderdelen:
            type: select
            label: Programma-onderdeel
            values: programmaonderdelen/name
            keys: id
            sort: name
            autocomplete: true
            limit: 2000
        programmas:
            type: select
            label: Programma
            postfix: "Bij welke editie van GWO of HCTS hoort dit?"
            values: programma/title
            keys: id
        speellokatie:
            type: select
            label: Locatie
            values:
                '': '-'
                bolder-zaal: "De Bolder zaal"
                bolder-cafe: "De Bolder café"
                ruige-plak: 'Ruige Plak'
                '-': '-'
                armhuis: 'Armhuis'
                bolder-restaurant: 'De Bolder restaurant'
                bolder-terras: 'De Bolder terras'
                bos: 'Bospodium'
                bospodium: 'Bospodium'
                de-bolder: 'De Bolder'
                fortweg: 'Fortweg'
                kerk-sportveld: 'Kerk Sportveld'
                kerk: 'Kerk'
                kolder: 'De Kolder'
                kunst: 'Kunst'
                naar-buiten: 'Naar Buiten'
                platte-kar: 'De Platte Kar'
                podium-vlieland: 'Podium Vlieland'
                pukkel: 'De Pukkel, Sportveld'
                sportveld: 'Sportveld'
                stoep: 'De Ouwe Stoep'
                strand: 'Strand'
                tokkelbaan: 'Tokkelbaan'
                vuurboetsduin: 'Vuurboetsduin'
        class:
            type: select
            values: 
             '': '(standaard)'
             'dj': 'DJ'
             'kunst': 'Kunst'
            label: Weergave in blokkenschema
            postfix: "<small>Dit bepaalt de kleur / weergave van het blokje, in het blokkenschema in de webapp.</small>"
    viewless: true
    default_status: published
    sort: starttijd
    recordsperpage: 100
    listing_records: 100
    searchable: false # Toon niet in "search"
    # show_in_menu: false # Toon niet in de sidebar in Bolt
    # show_on_dashboard: false # Toon niet op dashboard
    icon_many: "fa:music"
    icon_one: "fa:music"

pagina:
    name: Paginas
    singular_name: Pagina
    slug: paginas
    singular_slug: pagina
    description: "Losse paginas die gebruikt worden voor onderdelen als het contact formulier"
    fields:
        title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
        body:
            type: html
        image:
            type: image
            group: media
        template:
            type: templateselect
    record_template: record.twig
    listing_template: listing.twig
    show_on_dashboard: false
