speeltijden:
    name: Speeltijden
    singular_name: Speeltijd
    fields:
        title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
        starttijd:
            type: datetime
            variant: inline
            label: Speeldag en starttijd
            postfix: AM is voor de middag, PM is na de middag
        lengte:
            type: integer
            variant: inline
            label: Speelduur
            postfix: "Lengte van het optreden / performance. In minuten, dus '2 uur' is '120'."
        programmaonderdelen:
            type: select
            label: Programma-onderdeel
            values: programmaonderdelen/name
            keys: slug
            sort: name
            autocomplete: true
            limit: 2000
        programmas:
            type: select
            label: Programma
            postfix: "Bij welke editie van GWO of HCTS hoort dit?"
            values: programmas/title
            keys: slug
        speellokatie:
            type: select
            label: Locatie
            values:
                '': '-'
                bolder-zaal: "De Bolder zaal"
                bolder-cafe: "De Bolder café"
                ruige-plak: 'Ruige Plak'
                '-': '-'
                armhuis: 'Armhuis'
                bolder-restaurant: 'De Bolder restaurant'
                bolder-terras: 'De Bolder terras'
                bos: 'Bospodium'
                bospodium: 'Bospodium'
                de-bolder: 'De Bolder'
                fortweg: 'Fortweg'
                kerk-sportveld: 'Kerk Sportveld'
                kerk: 'Kerk'
                kolder: 'De Kolder'
                kunst: 'Kunst'
                naar-buiten: 'Naar Buiten'
                platte-kar: 'De Platte Kar'
                podium-vlieland: 'Podium Vlieland'
                pukkel: 'De Pukkel, Sportveld'
                sportveld: 'Sportveld'
                stoep: 'De Ouwe Stoep'
                strand: 'Strand'
                tokkelbaan: 'Tokkelbaan'
                vuurboetsduin: 'Vuurboetsduin'
    viewless: true
    default_status: published
    sort: -starttijd


programmas:
    name: Programmas
    singular_name: Programma
    fields:
        title:
            type: text
            class: large
            group: Informatie
        slug:
            type: slug
            uses: title
        image:
            type: image
        teaser:
            type: html
            height: 150px
        body:
            type: html
            height: 300px
        datum:
            type: date
            postfix: "De datum van deze editie. (om te kunnen sorteren)"
    taxonomy: [ chapters ]
    sort: -datum
    recordsperpage: 100
    record_template: programma.twig


programmaonderdelen:
    name: Programmaonderdelen
    singular_name: Programmaonderdeel
    fields:
        name:
            type: text
            class: large
            group: "Naam en zo."
        slug:
            type: slug
            uses: name
        description:
            type: html
            height: 150px
            label: Bandtekstje
        image:
            type: image
            label: Afbeelding
        showphotographer:
            type: text
            variant: inline
            label: Credit fotograaf
        url:
            prefix: "<hr><h3>Links, embeds, etc.</h3>"
            type: text
            variant: inline
            label: Website artiest of project
        spotify_link:
            type: text
            variant: inline
            label: Spotify url (http link)
        embed:
            type: text
            variant: inline
            label: Embedcode
            postfix: Ruimte voor een embedcode (bijv. Soundcloud)
        video:
            type: video
            label: Plak Vimeo of Youtube url (geen embedcode dus)
        videotitle:
            type: text
            variant: inline
            label: Omschrijving van de video
        oldvideo:
            type: text
            variant: inline
            label: oude video
            prefix: "<h2>LET OP!! Dit is de <em>oude meuk</em>!</h2><p>Deze wordt op de nieuwe site niet meer gebruikt en staat hier alleen om dingen in terug te zoeken enzo. Hieronder dingen aanpassen heeft geen zin.</p>"
            postfix: LET OP! Als hier een link instaat, plak deze dan met de hand naar 'Plak Vimeo of Youtube url', hierboven.
            group: "Oude meuk"
        starttijd:
            prefix: "<hr>"
            type: datetime
            variant: inline
            label: Speeldag en starttijd
            postfix: AM is voor de middag, PM is na de middag
        eindtijd:
            type: datetime
            variant: inline
            label: Eindtijd
        speellokatie:
            type: text
            class: narrow
            label: Locatie
        starttijd2:
            prefix: "<hr>"
            type: datetime
            variant: inline
            label: Speeldag en starttijd 2
            postfix: AM is voor de middag, PM is na de middag
        eindtijd2:
            type: datetime
            variant: inline
            label: Eindtijd 2
        speellokatie2:
            type: text
            class: narrow
            label: Locatie 2
        starttijd3:
            prefix: "<hr>"
            type: datetime
            variant: inline
            label: Speeldag en starttijd 3
            postfix: AM is voor de middag, PM is na de middag
        eindtijd3:
            type: datetime
            variant: inline
            label: Eindtijd 3
        speellokatie3:
            type: text
            class: narrow
            label: Locatie 3
            postfix: "<hr style='border-color:red'>"
        speeldag:
            type: text
            variant: inline
            class: narrow
        speeltijd:
            type: text
            variant: inline
            class: narrow
        speelduur:
            type: text
            variant: inline
            class: narrow
        speeldag2:
            type: text
            variant: inline
            class: narrow
        speeltijd2:
            type: text
            variant: inline
            class: narrow
        speellokatie2:
            type: text
            variant: inline
            class: narrow
        speelduur2:
            type: text
            variant: inline
            class: narrow
        speeldag3:
            type: text
            variant: inline
            class: narrow
        speeltijd3:
            type: text
            variant: inline
            class: narrow
        speellokatie3:
            type: text
            variant: inline
            class: narrow
        speelduur3:
            type: text
            variant: inline
            class: narrow
        speeldag4:
            type: text
            variant: inline
            class: narrow
        speeltijd4:
            type: text
            variant: inline
            class: narrow
        speellokatie4:
            type: text
            variant: inline
            class: narrow
        speelduur4:
            type: text
            variant: inline
            class: narrow
    taxonomy: [ tags, programmatypen ]
    recordsperpage: 20

pagina:
    name: Paginas
    singular_name: Pagina
    slug: paginas
    singular_slug: pagina
    description: "Losse paginas die gebruikt worden voor onderdelen als het contact formulier"
    fields:
        title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
        body:
            type: html
        image:
            type: image
            group: media
        template:
            type: templateselect
    record_template: record.twig
    listing_template: listing.twig
    show_on_dashboard: false
